# Generated by Django 5.2.8 on 2025-12-30 14:56

import django.db.models.deletion
import django.utils.timezone
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='contracts', to='inventory.productcategory')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='jobs.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tickets_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returnable', models.BooleanField(default=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='jobs.deliveryticket')),
            ],
            options={
                'unique_together': {('ticket', 'item')},
            },
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='items',
            field=models.ManyToManyField(related_name='delivery_tickets', through='jobs.DeliveryTicketItem', to='inventory.inventoryitem'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('1101', '1101 (Fishing)'), ('1102', '1102 (Rental)'), ('1103', '1103 (Jars)'), ('1104', '1104 (Machine shop)'), ('1105', '1105 (Thru Tubing)')], max_length=4)),
                ('job_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('rig', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('well', models.CharField(max_length=100)),
                ('trans', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportation')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tickets', to='jobs.job'),
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_attachments/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deliveryticket',
            unique_together={('job', 'ticket_number')},
        ),
        migrations.CreateModel(
            name='ReceivingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to=jobs.models.inspection_report_upload_path)),
                ('is_fully_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='receiving_tickets', to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_tickets', to='jobs.job')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_tickets_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'ticket_number')},
            },
        ),
    ]
