# Generated by Django 5.2.8 on 2025-11-26 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='contracts', to='inventory.productcategory')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='jobs.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('1101', '1101 (Rental)'), ('1102', '1102 (Fishing)'), ('1103', '1103 (Other Type A)'), ('1104', '1104 (Other Type B)')], max_length=4)),
                ('job_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('rig', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('trans', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportation')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('well', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='delivery_tickets', to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tickets', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='job_attachments/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='receiving_tickets', to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_tickets', to='jobs.job')),
            ],
        ),
    ]
