# Generated by Django 5.2.8 on 2025-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='trans',
        ),
        migrations.AlterField(
            model_name='deliveryticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1101', '1101 (Fishing)'), ('1102', '1102 (Rental)'), ('1103', '1103 (Jars)'), ('1104', '1104 (Machine shop)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='PENDING', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='rig',
            field=models.CharField(default='PENDING', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='well',
            field=models.CharField(default='PENDING', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivingticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryticket',
            unique_together={('job', 'ticket_number')},
        ),
        migrations.AlterUniqueTogether(
            name='receivingticket',
            unique_together={('job', 'ticket_number')},
        ),
    ]
