# Generated by Django 5.2.8 on 2025-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_trans_alter_deliveryticket_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='trans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportation'),
        ),
    ]
