# Generated by Django 5.2.8 on 2025-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_deliveryticket_created_by_receivingticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1101', '1101 (Fishing)'), ('1102', '1102 (Rental)'), ('1103', '1103 (Jars)'), ('1104', '1104 (Machine shop)'), ('1105', 'Thru Tubing')], max_length=4),
        ),
    ]
