# Generated by Django 5.2.8 on 2025-12-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_status'),
        ('jobs', '0005_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1101', '1101 (Fishing)'), ('1102', '1102 (Rental)'), ('1103', '1103 (Jars)'), ('1104', '1104 (Machine shop)'), ('1105', '1105 (Thru Tubing)')], max_length=4),
        ),
        migrations.CreateModel(
            name='DeliveryTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returnable', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='jobs.deliveryticket')),
            ],
            options={
                'unique_together': {('ticket', 'item')},
            },
        ),
        migrations.AlterField(
            model_name='deliveryticket',
            name='items',
            field=models.ManyToManyField(related_name='delivery_tickets', through='jobs.DeliveryTicketItem', to='inventory.inventoryitem'),
        ),
    ]
