# Generated by Django 5.2.8 on 2025-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_job_type_deliveryticketitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobattachment',
            name='file',
            field=models.FileField(upload_to='job_attachments/'),
        ),
    ]
