# Generated by Django 5.2.8 on 2025-12-17 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobattachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryticket',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tickets_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receivingticket',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_tickets_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivingticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
