# Generated by Django 5.2.8 on 2025-12-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_deliveryticket_modified_by_deliveryticket_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingticket',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to='inspection_reports/'),
        ),
    ]
