# Generated by Django 5.2.8 on 2025-12-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_receivingticket_inspection_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingticket',
            name='is_fully_verified',
            field=models.BooleanField(default=False),
        ),
    ]
