# Generated by Django 5.2.8 on 2025-12-23 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_status'),
        ('jobs', '0011_alter_deliveryticketitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryticketitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
    ]
