# Generated by Django 5.2.8 on 2025-12-25 10:53

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_deliveryticketitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivingticket',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.inspection_report_upload_path),
        ),
    ]
