# Generated by Django 5.2.8 on 2025-12-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_status'),
        ('jobs', '0013_alter_receivingticket_inspection_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryticketitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
    ]
