# Generated by Django 5.2.8 on 2025-11-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(blank=True, help_text="e.g., 'pcs', 'joint', 'meter'", max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(choices=[('maadi-yard', 'Maadi Yard'), ('abu-rudies-yard', 'Abu Rudies Yard')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_job', 'On Job'), ('re-cut', 'Re-cut'), ('lih-dbr', 'LIH-DBR')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.productcategory')),
            ],
            options={
                'ordering': ['category__name', 'serial_number'],
            },
        ),
    ]
