# Generated by Django 5.2.8 on 2025-11-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_job', 'On Job'), ('re-cut', 'Re-cut'), ('lih-dbr', 'LIH-DBR'), ('pending_inspection', 'Pending Inspection')], default='available', max_length=20),
        ),
    ]
