# Generated by Django 5.2.8 on 2025-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
