# Generated by Django 5.2.8 on 2025-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_job', 'On Job'), ('re-cut', 'Re-cut'), ('lih-dbr', 'LIH-DBR'), ('pending_inspection', 'Pending Inspection'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
