# Generated by Django 5.2.8 on 2025-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_job', 'On Job'), ('re-cut', 'Re-cut'), ('lih', 'LIH'), ('junk', 'Junk'), ('pending_inspection', 'Pending Inspection'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
