# Generated by Django 5.2.8 on 2025-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='recut_reason',
            field=models.CharField(blank=True, help_text='Reason for re-cut, if applicable.', max_length=255, null=True),
        ),
    ]
